insert into public.fish (
  common_name,
  scientific_name,
  family,
  description,
  image_url,
  temp_min,
  temp_max,
  ph_min,
  ph_max,
  hardness_min,
  hardness_max,
  size_adult_cm,
  lifespan,
  diet,
  temperament,
  tank_level_min,
  difficulty_level,
  rarity,
  compatible_with,
  incompatible_with,
  care_notes,
  tags,
  created_at,
  updated_at
) values
  (
    'Guppy',
    'Poecilia reticulata',
    'Poeciliidae',
    'Pez pequeno y activo, ideal para acuarios comunitarios.',
    'https://images.example.com/fish/guppy.jpg',
    22.0,
    28.0,
    7.0,
    8.2,
    10,
    25,
    4.0,
    '2-3 anios',
    'omnivoro',
    'pacifico',
    40,
    1,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Mantener en grupos y con plantas para refugio.',
    '{tropical,comunitario}',
    now(),
    now()
  ),
  (
    'Betta splendens',
    'Betta splendens',
    'Osphronemidae',
    'Pez territorial con colores intensos.',
    'https://images.example.com/fish/betta.jpg',
    24.0,
    30.0,
    6.0,
    7.5,
    5,
    15,
    6.5,
    '3-4 anios',
    'carnivoro',
    'agresivo',
    20,
    2,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'No mezclar con otros machos.',
    '{tropical,solo}',
    now(),
    now()
  ),
  (
    'Neon tetra',
    'Paracheirodon innesi',
    'Characidae',
    'Cardumen pequeno y brillante.',
    'https://images.example.com/fish/neon-tetra.jpg',
    20.0,
    26.0,
    6.0,
    7.2,
    2,
    12,
    3.5,
    '3-5 anios',
    'omnivoro',
    'pacifico',
    50,
    2,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Mantener en cardumen de al menos 8.',
    '{tropical,cardumen}',
    now(),
    now()
  ),
  (
    'Cardinal tetra',
    'Paracheirodon axelrodi',
    'Characidae',
    'Similar al neon, mas intenso y rojo.',
    'https://images.example.com/fish/cardinal-tetra.jpg',
    24.0,
    28.0,
    5.5,
    7.0,
    2,
    10,
    4.0,
    '4-5 anios',
    'omnivoro',
    'pacifico',
    60,
    3,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Prefiere agua blanda y estable.',
    '{tropical,cardumen}',
    now(),
    now()
  ),
  (
    'Zebra danio',
    'Danio rerio',
    'Cyprinidae',
    'Pez resistente y activo.',
    'https://images.example.com/fish/zebra-danio.jpg',
    18.0,
    26.0,
    6.5,
    7.5,
    5,
    20,
    5.0,
    '3-4 anios',
    'omnivoro',
    'pacifico',
    60,
    1,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Aprecia corriente moderada.',
    '{tropical,cardumen}',
    now(),
    now()
  ),
  (
    'Goldfish',
    'Carassius auratus',
    'Cyprinidae',
    'Pez de agua fria, requiere mucho oxigeno.',
    'https://images.example.com/fish/goldfish.jpg',
    16.0,
    22.0,
    7.0,
    8.0,
    8,
    20,
    25.0,
    '10-15 anios',
    'omnivoro',
    'pacifico',
    120,
    3,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'No mezclar con peces tropicales.',
    '{agua_fria}',
    now(),
    now()
  ),
  (
    'Angelfish',
    'Pterophyllum scalare',
    'Cichlidae',
    'Cicilido elegante y territorial.',
    'https://images.example.com/fish/angelfish.jpg',
    24.0,
    28.0,
    6.0,
    7.5,
    3,
    12,
    15.0,
    '8-10 anios',
    'omnivoro',
    'semiagressivo',
    150,
    3,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Evitar peces muy pequenos.',
    '{tropical,cicilido}',
    now(),
    now()
  ),
  (
    'Corydoras',
    'Corydoras paleatus',
    'Callichthyidae',
    'Pez de fondo pacifico.',
    'https://images.example.com/fish/corydoras.jpg',
    20.0,
    26.0,
    6.5,
    7.5,
    2,
    15,
    7.0,
    '5-8 anios',
    'omnivoro',
    'pacifico',
    80,
    2,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Usar sustrato suave para proteger barbillones.',
    '{fondo,cardumen}',
    now(),
    now()
  ),
  (
    'Platy',
    'Xiphophorus maculatus',
    'Poeciliidae',
    'Pez viviparo, facil de criar.',
    'https://images.example.com/fish/platy.jpg',
    22.0,
    27.0,
    7.0,
    8.2,
    10,
    25,
    6.0,
    '3-4 anios',
    'omnivoro',
    'pacifico',
    60,
    1,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Mantener proporcion de hembras mayor que machos.',
    '{tropical,viviparo}',
    now(),
    now()
  ),
  (
    'Molly',
    'Poecilia sphenops',
    'Poeciliidae',
    'Pez viviparo activo y resistente.',
    'https://images.example.com/fish/molly.jpg',
    24.0,
    28.0,
    7.2,
    8.5,
    10,
    30,
    8.0,
    '3-5 anios',
    'omnivoro',
    'pacifico',
    80,
    2,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Prefiere agua con algo de dureza.',
    '{tropical,viviparo}',
    now(),
    now()
  ),
  (
    'Oscar',
    'Astronotus ocellatus',
    'Cichlidae',
    'Cicilido grande y agresivo.',
    'https://images.example.com/fish/oscar.jpg',
    23.0,
    28.0,
    6.5,
    7.5,
    5,
    20,
    30.0,
    '10-15 anios',
    'carnivoro',
    'agresivo',
    250,
    4,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Requiere filtracion potente.',
    '{cicilido,grande}',
    now(),
    now()
  ),
  (
    'Discus',
    'Symphysodon aequifasciatus',
    'Cichlidae',
    'Pez delicado de aguas blandas.',
    'https://images.example.com/fish/discus.jpg',
    27.0,
    30.0,
    5.5,
    7.0,
    1,
    8,
    15.0,
    '8-10 anios',
    'omnivoro',
    'semiagressivo',
    200,
    5,
    'raro',
    '{}'::uuid[],
    '{}'::uuid[],
    'Cambios de agua frecuentes.',
    '{tropical,delicado}',
    now(),
    now()
  ),
  (
    'Clownfish',
    'Amphiprion ocellaris',
    'Pomacentridae',
    'Pez marino iconico y resistente.',
    'https://images.example.com/fish/clownfish.jpg',
    24.0,
    28.0,
    8.0,
    8.4,
    7,
    12,
    10.0,
    '6-10 anios',
    'omnivoro',
    'pacifico',
    120,
    3,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Requiere agua marina estable.',
    '{marino}',
    now(),
    now()
  ),
  (
    'Blue tang',
    'Paracanthurus hepatus',
    'Acanthuridae',
    'Pez marino activo y nadador.',
    'https://images.example.com/fish/blue-tang.jpg',
    24.0,
    28.0,
    8.0,
    8.4,
    8,
    12,
    25.0,
    '8-12 anios',
    'herbivoro',
    'semiagressivo',
    300,
    4,
    'raro',
    '{}'::uuid[],
    '{}'::uuid[],
    'Necesita espacio para nadar.',
    '{marino}',
    now(),
    now()
  ),
  (
    'Cherry barb',
    'Puntius titteya',
    'Cyprinidae',
    'Pez pequeno y activo con color rojo.',
    'https://images.example.com/fish/cherry-barb.jpg',
    22.0,
    27.0,
    6.0,
    7.5,
    5,
    15,
    5.0,
    '4-6 anios',
    'omnivoro',
    'pacifico',
    60,
    2,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Mantener en grupos.',
    '{tropical,cardumen}',
    now(),
    now()
  ),
  (
    'Siamese algae eater',
    'Crossocheilus oblongus',
    'Cyprinidae',
    'Ayuda a controlar algas.',
    'https://images.example.com/fish/siamese-algae-eater.jpg',
    22.0,
    26.0,
    6.5,
    7.5,
    5,
    15,
    14.0,
    '8-10 anios',
    'herbivoro',
    'pacifico',
    100,
    3,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Requiere espacio y corriente moderada.',
    '{tropical,alga}',
    now(),
    now()
  ),
  (
    'Kuhli loach',
    'Pangio kuhlii',
    'Cobitidae',
    'Pez de fondo nocturno.',
    'https://images.example.com/fish/kuhli-loach.jpg',
    24.0,
    28.0,
    5.5,
    7.0,
    2,
    10,
    10.0,
    '8-10 anios',
    'omnivoro',
    'pacifico',
    80,
    3,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Usar refugios y sustrato suave.',
    '{fondo,nocturno}',
    now(),
    now()
  ),
  (
    'Boesemani rainbowfish',
    'Melanotaenia boesemani',
    'Melanotaeniidae',
    'Coloracion intensa y activa.',
    'https://images.example.com/fish/boesemani-rainbow.jpg',
    24.0,
    28.0,
    7.0,
    8.0,
    8,
    20,
    12.0,
    '5-8 anios',
    'omnivoro',
    'pacifico',
    120,
    3,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Mantener en cardumen.',
    '{tropical,cardumen}',
    now(),
    now()
  ),
  (
    'Dwarf gourami',
    'Trichogaster lalius',
    'Osphronemidae',
    'Pez de superficie con colores vivos.',
    'https://images.example.com/fish/dwarf-gourami.jpg',
    24.0,
    28.0,
    6.0,
    7.5,
    4,
    12,
    7.0,
    '4-6 anios',
    'omnivoro',
    'semiagressivo',
    80,
    3,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Evitar companeros muy agresivos.',
    '{tropical,laberinto}',
    now(),
    now()
  ),
  (
    'Pleco comun',
    'Hypostomus plecostomus',
    'Loricariidae',
    'Pez de fondo que crece mucho.',
    'https://images.example.com/fish/pleco.jpg',
    22.0,
    27.0,
    6.5,
    7.5,
    6,
    20,
    35.0,
    '10-15 anios',
    'herbivoro',
    'pacifico',
    250,
    4,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Necesita troncos y refugios.',
    '{fondo,alga}',
    now(),
    now()
  ),
  (
    'Ramirezi',
    'Mikrogeophagus ramirezi',
    'Cichlidae',
    'Cicilido pequeno y colorido.',
    'https://images.example.com/fish/ramirezi.jpg',
    25.0,
    30.0,
    5.5,
    7.0,
    1,
    8,
    7.0,
    '3-4 anios',
    'omnivoro',
    'semiagressivo',
    80,
    4,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Requiere agua limpia y estable.',
    '{tropical,cicilido}',
    now(),
    now()
  ),
  (
    'Otocinclus',
    'Otocinclus affinis',
    'Loricariidae',
    'Pez pequeno come algas.',
    'https://images.example.com/fish/otocinclus.jpg',
    22.0,
    26.0,
    6.0,
    7.5,
    3,
    12,
    4.0,
    '3-5 anios',
    'herbivoro',
    'pacifico',
    60,
    3,
    'comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Mantener en grupos pequenos.',
    '{fondo,alga}',
    now(),
    now()
  ),
  (
    'Endler guppy',
    'Poecilia wingei',
    'Poeciliidae',
    'Variante pequena y colorida del guppy.',
    'https://images.example.com/fish/endler.jpg',
    22.0,
    28.0,
    7.0,
    8.0,
    10,
    25,
    3.0,
    '2-3 anios',
    'omnivoro',
    'pacifico',
    40,
    1,
    'poco_comun',
    '{}'::uuid[],
    '{}'::uuid[],
    'Ideal para nano acuarios.',
    '{tropical,nano}',
    now(),
    now()
  );
